--- #YAML:1.0
name:                POEx-URI
version:             0.0300
abstract:            URI extension for POE event specfiers
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    URI:                           1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Philip Gwyn <gwyn -at- cpan.org>
